import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {installLegacyStockComponentsRuntime,stockSaleFingerprint,matchCompletedStockSale,correctionFromVerifiedUpdate} from '../src/compat/legacy-stock-components-runtime.js';

function memoryStorage(){let value=null;return{read:()=>structuredClone(value),write:v=>(value=structuredClone(v)),dump:()=>structuredClone(value)}}
function fixture({cart=[{id:'P1',q:1,p:5000}],actor={id:'cashier-1',name:'Kasir',role:'transaksi'},mapping={},stockItems={},baseResult='TX1',transactions={}}={}){
  let baseCalls=0,intervalCalls=0,financialCalls=0;const storage=memoryStorage(),applied=[],restores=[];let txs=structuredClone(transactions);
  const production={async verifiedUpdate(){financialCalls++;return 'FINANCIAL_COMMITTED'}};
  const runtime={localStorage:storage,console:{warn(){}},setTimeout(){return 0},setInterval(){intervalCalls++;return 1},showToast(){},SJProductionHardening:production,async processTransaction(){baseCalls++;return typeof baseResult==='function'?baseResult({txs,setTxs:v=>txs=structuredClone(v)}):baseResult}};
  const repository={async readProductStockComponents(id){return structuredClone(mapping[id]||{})},async readStockItem(id){return structuredClone(stockItems[id]||{name:id,unit:'pcs'})}};
  const writer={async applyCompletedSale(input){applied.push(structuredClone(input));return{status:'COMPLETED',result:'APPLIED'}},async restoreRefund(input){restores.push({kind:'REFUND',input:structuredClone(input)});return{status:'COMPLETED',result:'RESTORED'}},async restoreVoid(input){restores.push({kind:'VOID',input:structuredClone(input)});return{status:'COMPLETED',result:'RESTORED'}}};
  const legacyContext={snapshotSale:()=>({shiftKey:'2026-09-19-S1',cart:structuredClone(cart),actor:structuredClone(actor),preTxKeys:['OLD'],capturedAt:1000})};
  const transactionReader={async readById(_shift,id){return structuredClone(txs[id]||null)},async readRecent(){return structuredClone(txs)}};
  return{runtime,production,repository,writer,legacyContext,transactionReader,storage,applied,restores,setTxs:v=>txs=structuredClone(v),baseCalls:()=>baseCalls,financialCalls:()=>financialCalls,intervalCalls:()=>intervalCalls};
}
function install(f){return installLegacyStockComponentsRuntime(f.runtime,{inventoryRepository:f.repository,stockComponentWriter:f.writer,legacyContext:f.legacyContext,transactionReader:f.transactionReader,storage:f.storage,now:()=>1500,autoRecover:false})}
function refundUpdates(returnStock=true){return{'2026-09-19-S1/tx/TX1/lastRefundId':'RF1','global/refunds/RF1':{id:'RF1',shift:'2026-09-19-S1',returnStock,items:[{id:'P1',q:1,lineIndex:0}]},'global/auditLogs/A1':{action:'REFUND',userId:'owner-1',user:'Owner',role:'manajemen'}}}
function voidUpdates(){return{'2026-09-19-S1/tx/TX2/voidId':'VOID1','global/auditLogs/A2':{action:'VOID',userId:'owner-1',user:'Owner',role:'manajemen'}}}

test('fingerprint normalizes normal and recipe product identity',()=>{assert.equal(stockSaleFingerprint([{id:'P1',q:2,p:0}]),JSON.stringify([['P:P1',2,0]]));assert.equal(stockSaleFingerprint([{id:'V1',baseProductId:'P2',recipeVariantId:'R1',inventoryMode:'RECIPE',q:1,p:7000}]),JSON.stringify([['R:P2:R1',1,7000]]))});
test('matcher requires new key + COMPLETED + fingerprint + bounded timestamp',()=>{const fp=stockSaleFingerprint([{id:'P1',q:1,p:5000}]);const hit=matchCompletedStockSale({beforeKeys:['OLD'],fingerprint:fp,startedAt:1000,endedAt:1500,after:{NEW:{status:'COMPLETED',ts:1200,cartData:[{id:'P1',q:1,p:5000}]}}});assert.equal(hit.txId,'NEW')});
test('no mapping delegates to base exactly once and adds no polling',async()=>{const f=fixture({baseResult:true});install(f);assert.equal(await f.runtime.processTransaction(),true);assert.equal(f.baseCalls(),1);assert.equal(f.applied.length,0);assert.equal(f.intervalCalls(),0)});
test('mapped/Rp0/role/concurrent/Recipe coverage remains green after correction integration',async()=>{const cart=[{id:'P1',q:1,p:0}],f=fixture({cart,actor:{id:'cashier',name:'Kasir',role:'transaksi'},mapping:{P1:{CUP:{stockItemId:'CUP',qtyPerUnit:1,active:true}}},transactions:{TX1:{status:'COMPLETED',ts:1200,cartData:cart,inventoryRecipeAppliedConsumption:{SUGAR:1}}}});install(f);await f.runtime.processTransaction();assert.equal(f.applied.length,1);assert.equal(f.applied[0].actor.role,'transaksi')});

test('correction parser derives refund identity/lines only from committed update payload',()=>{const c=correctionFromVerifiedUpdate(refundUpdates(),'REFUND_ATOMIC_TIMEOUT');assert.equal(c.kind,'REFUND');assert.equal(c.shiftKey,'2026-09-19-S1');assert.equal(c.txId,'TX1');assert.equal(c.refundId,'RF1');assert.deepEqual(c.refundLines,[{lineIndex:0,productId:'P1',q:1}]);assert.equal(c.actor.role,'manajemen');assert.equal(c.returnStock,true)});

test('financial refund commit completes before stock restore hook and returns financial result',async()=>{const f=fixture();install(f);const out=await f.production.verifiedUpdate(refundUpdates(),'REFUND_ATOMIC_TIMEOUT',async()=>true);assert.equal(out,'FINANCIAL_COMMITTED');assert.equal(f.financialCalls(),1);assert.equal(f.restores.length,1);assert.equal(f.restores[0].kind,'REFUND');assert.equal(f.restores[0].input.refundId,'RF1')});

test('failed financial correction never triggers stock restore',async()=>{const f=fixture();f.production.verifiedUpdate=async()=>{throw Object.assign(new Error('financial failed'),{code:'FINANCIAL_FAILED'})};install(f);await assert.rejects(f.production.verifiedUpdate(refundUpdates(),'REFUND_ATOMIC_TIMEOUT',async()=>true),/financial failed/);assert.equal(f.restores.length,0)});

test('refund that explicitly does not return physical stock does not restore Product Stock Components',async()=>{const f=fixture();install(f);const out=await f.production.verifiedUpdate(refundUpdates(false),'REFUND_ATOMIC_TIMEOUT',async()=>true);assert.equal(out,'FINANCIAL_COMMITTED');assert.equal(f.financialCalls(),1);assert.equal(f.restores.length,0);assert.doesNotMatch(JSON.stringify(f.storage.dump()),/RF1/)});

test('void commit triggers exactly the historical application restore identity',async()=>{const f=fixture();install(f);const out=await f.production.verifiedUpdate(voidUpdates(),'VOID_ATOMIC_TIMEOUT',async()=>true);assert.equal(out,'FINANCIAL_COMMITTED');assert.equal(f.restores.length,1);assert.equal(f.restores[0].kind,'VOID');assert.equal(f.restores[0].input.txId,'TX2');assert.equal(f.restores[0].input.voidId,'VOID1')});

test('historical correction with no stock application does not invent restore evidence',async()=>{const f=fixture();f.writer.restoreRefund=async()=>{throw Object.assign(new Error('missing'),{code:'STOCK_RESTORE_APPLICATION_NOT_FOUND'})};install(f);const out=await f.production.verifiedUpdate(refundUpdates(),'REFUND_ATOMIC_TIMEOUT',async()=>true);assert.equal(out,'FINANCIAL_COMMITTED');assert.doesNotMatch(JSON.stringify(f.storage.dump()),/RF1/)});

test('transient stock restore failure never rolls back financial commit and becomes recoverable attention',async()=>{const f=fixture();let attempts=0;f.writer.restoreRefund=async input=>{attempts++;if(attempts===1)throw Object.assign(new Error('network'),{code:'NETWORK'});f.restores.push({kind:'REFUND',input});return{status:'COMPLETED',result:'RECOVERED'}};install(f);const out=await f.production.verifiedUpdate(refundUpdates(),'REFUND_ATOMIC_TIMEOUT',async()=>true);assert.equal(out,'FINANCIAL_COMMITTED');assert.equal(f.financialCalls(),1);assert.match(JSON.stringify(f.storage.dump()),/RF1/);const recovered=await f.runtime.__SJ_LEGACY_STOCK_COMPONENTS_RUNTIME.recoverPending();assert.equal(recovered[0].status,'COMPLETED');assert.doesNotMatch(JSON.stringify(f.storage.dump()),/RF1/)});

test('unrelated verifiedUpdate is untouched',async()=>{const f=fixture();install(f);const out=await f.production.verifiedUpdate({'x':1},'EXPENSE_VERIFIED_TIMEOUT',async()=>true);assert.equal(out,'FINANCIAL_COMMITTED');assert.equal(f.restores.length,0)});

test('stop restores sale and verifiedUpdate owners',()=>{const f=fixture(),sale=f.runtime.processTransaction,verified=f.production.verifiedUpdate,api=install(f);assert.notEqual(f.runtime.processTransaction,sale);assert.notEqual(f.production.verifiedUpdate,verified);api.stop();assert.equal(f.runtime.processTransaction,sale);assert.equal(f.production.verifiedUpdate,verified)});

test('build/bootstrap contract keeps frozen tail while installing classic context before module runtime',()=>{const build=readFileSync('scripts/build-ref01.mjs','utf8'),bootstrap=readFileSync('src/app/ref01-bootstrap.js','utf8');assert.match(build,/STOCK_COMPONENT_CONTEXT_ENTRY/);const candidate=build.slice(build.indexOf('const candidate='));assert.ok(candidate.indexOf('${STOCK_COMPONENT_CONTEXT_ENTRY}')<candidate.indexOf('${CLASSIC_ENTRY}'));assert.match(candidate,/\$\{S10A_CLASSIC_ENTRY\}\\n\$\{QRIS_MANUAL_ENTRY\}\\n\$\{ENTRY\}/);assert.match(bootstrap,/installLegacyStockComponentsRuntime/);assert.match(bootstrap,/legacyStockComponentsRuntime/)});

test('runtime/context remain one-shot: no permanent transaction listener or polling loop',()=>{const runtime=readFileSync('src/compat/legacy-stock-components-runtime.js','utf8'),context=readFileSync('src/compat/legacy-stock-components-context.js','utf8');assert.doesNotMatch(runtime,/setInterval\s*\(/);assert.doesNotMatch(context,/setInterval\s*\(/);assert.doesNotMatch(runtime,/\.on\s*\(\s*['\"](?:value|child_)/);assert.doesNotMatch(context,/\.on\s*\(\s*['\"](?:value|child_)/)});
