import { installSc03Runtime } from './app/bootstrap.js';
import { installSc04Runtime } from './app/sc04-bootstrap.js';
import { installRef01Runtime } from './app/ref01-bootstrap.js';
import { installP4FinanceRuntime } from './app/p4-finance-bootstrap.js';
import { installQrisDeferredSettlementRuntime } from './app/qris-deferred-settlement-bootstrap.js';
import { installRc01ReceiptOutput } from './ui/rc01-receipt-output.js';
const sc03=installSc03Runtime(globalThis);
const sc04=installSc04Runtime(globalThis,{sc03});
const p4=installP4FinanceRuntime(globalThis,{sc03});
const qrisDeferred=installQrisDeferredSettlementRuntime(globalThis,{p4});
const ref01=installRef01Runtime(globalThis,{sc03,sc04,p4});
installRc01ReceiptOutput(globalThis);
sc04.ready.finally(()=>{try{ref01.enhance()}catch(_){}});
